Allow check for missing assignments of placeholder fake passwords to fail

diff --git a/.github/workflows/validate-data.yaml b/.github/workflows/validate-data.yaml
--- a/.github/workflows/validate-data.yaml
+++ b/.github/workflows/validate-data.yaml
@@ -51,9 +51,10 @@ jobs:
         run: |
           curl -fsSLo CardSchema.json '${{ secrets.CARD_SCHEMA_URL }}'
           python src/test_data_validation.py CardSchema.json data/cards
+        # No longer fails workflow until assignments.yaml can be properly maintained
       - name: Cards are not missing placeholder fake passwords
         if: success() || failure()
-        run: yarn check-for-missing-fake-password data/cards
+        run: yarn check-for-missing-fake-password data/cards || true
       - name: Rush Duel cards are not missing Japanese names
         if: success() || failure()
         run: yarn check-for-missing-names data/rush ja
